import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { findCountries } from '@/lib/dbClient';

interface PageProps {
	countries: unknown;
}

export default function Home({ countries }: PageProps) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.description}>
					<pre className={styles.code}>
						{JSON.stringify(countries, undefined, 4)}
					</pre>
				</div>
			</main>
		</>
	)
}

export async function getServerSideProps() {
	const results = await findCountries();

	return {
		props: {
			countries: results,
		},
	};
}
